### ISSUE TITLE
Tests for the CLI does not pass on windows

### ISSUE THREAD

**Issue by tregusti** [pgilad/leasot#45]
In either cygwin or cmd.exe.

They all fail with the same message.

```
  7) check cli should get no error exitCode if no todos or fixmes are found:
     Error: spawn UNKNOWN
      at exports._errnoException (util.js:890:11)
      at ChildProcess.spawn (internal/child_process.js:302:11)
      at Object.exports.spawn (child_process.js:367:9)
      at testCli (C:\code\leasot\tests\cli-spec.js:14:27)
      at Context.<anonymous> (C:\code\leasot\tests\cli-spec.js:135:9)
      at callFnAsync (C:\code\leasot\node_modules\mocha\lib\runnable.js:338:8)
      at Test.Runnable.run (C:\code\leasot\node_modules\mocha\lib\runnable.js:290:7)
      at Runner.runTest (C:\code\leasot\node_modules\mocha\lib\runner.js:422:10)
      at C:\code\leasot\node_modules\mocha\lib\runner.js:533:12
      at next (C:\code\leasot\node_modules\mocha\lib\runner.js:342:14)
      at C:\code\leasot\node_modules\mocha\lib\runner.js:352:7
      at next (C:\code\leasot\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\code\leasot\node_modules\mocha\lib\runner.js:320:5)
```

**Comment by pgilad** [comment]
Ouch, I haven't maintained this for windows. Can you help fix/find the issues?

**Comment by tregusti** [comment]
I will see what I can do. Currently trying to add some other features =)

**Comment by pgilad** [comment]
@tregusti Hey - any news on this? I'd love to get proper Windows support

**Comment by SeanSobey** [comment]
I came across this as well, I resolved this by changing `cli-spec.js`:
```js
function testCli(files, extraArgs, cb) {
    var args = files.map(getFixturePath).concat(extraArgs || []);

    var cp = childProcess.spawn('./bin/leasot.js', args, {
```
to:
```js
function testCli(files, extraArgs, cb) {
    var args = ['./bin/leasot.js'].concat(files.map(getFixturePath).concat(extraArgs || []));

    var cp = childProcess.spawn('node', args, {
```
Based on this [SO answer](https://stackoverflow.com/questions/43419893/how-do-i-fix-error-spawn-unknown-with-node-js-v7-8-0-on-windows-10).

**Comment by pgilad** [comment]
Finally fixed by https://github.com/pgilad/leasot/pull/87
